### ISSUE TITLE
Names matching wrong strings

### ISSUE THREAD

**Issue by johneakin** [nieroda/mcafeeBTCTradeBot#2]
Depending on the tweet, multiple names could be matched.
i.e. if the tweet happened to say
'Coin of the day: a new blockchain crypto, Reddcoin (RDD)'
I think this would actually match 'BLOCK' from the names list and incorrectly try to purchase this...

Might be better to Regex on 3/4/5 character length strings that are in Capitals, and then verify the regex match against the names list?

**Comment by nieroda** [comment]
Just removed the top ~30 coins, and removed BLOCK(temp bandaid to avoid issues). Thanks for comment. Will also do this later.

**Comment by johneakin** [comment]
Something like this:

let test = 'RDD coin of the day';
checkTweet(test);

function checkTweet(text){
  if (safeCheck) {
	var res = a.match('[A-Z][A-Z][A-Z]?[A-Z]?[A-Z]?');
	if(res != null && res.length>0)
	{
		for (var val of names) {
			if (res[0].includes(val) && text.toLowerCase().includes('coin of the day')) 
			{
				console.log(`${text} :: ${val}`);
				//polo.checkBalancesandBuy(val.toUpperCase());
				break;
			}
		}
	}
  } else {
    for (var val of names) {
      if (text.includes(val)) {
        console.log(`${text} :: ${val}`);
        //polo.checkBalancesandBuy(val.toUpperCase());
      }
    }
  }
}
