### ISSUE TITLE
Poloniex doesnt have enough available cryptos for trading

### ISSUE THREAD

**Issue by johneakin** [nieroda/mcafeeBTCTradeBot#3]
Perhaps better to use Bittrex?
I can't see any of McCafee's suggestions being tradable on Poloniex (It only seems to have the larger crypto's) unless I am mistaken?

Although i've just seen Bittrex is temporarily closed for new registrations

**Comment by johneakin** [comment]
YoBit.net seems to also be decent

**Comment by dekaru** [comment]
hitbtc and binance have a lot of coins too

**Comment by nieroda** [comment]
need testing for added bittrex support, will look into hitbtc and  yobit next (binance is closed also 👎  )
